### ISSUE TITLE
Research the available research surrounding the calculation methods

### ISSUE THREAD

**Issue by BaBrixx** [AAU-SW6-JABA/CDM-Server#6]
### OBS: This is a sub-issue of #5

**Comment by BaBrixx** [comment]
## Keywords:
1. RSSI: _Received Signal Strength Indicator_
2. Trialteration: _the use of distances (or "ranges") for determining the unknown position coordinates of a point of interest,_
3. 

## Literature that can be used as a guide as to how we should tackle the calculations:
1. Explanation and step-by-step guide using bluetooth (dbm): [Bluetooth positioning using RSSI and triangulation methods](https://www.researchgate.net/profile/Yapeng-Wang-5/publication/261056426_Bluetooth_positioning_using_RSSI_and_triangulation_methods/links/5b0fbe6a0f7e9b1ed703bf0a/Bluetooth-positioning-using-RSSI-and-triangulation-methods.pdf)
2. [The Accuracy of Propagation Models for Distance Measurement between WSN Nodes](https://ieeexplore.ieee.org/document/5367782)
3. Filtering for improved accuracy: [An RSSI Classification and Tracing Algorithm to Improve Trilateration-Based Positioning](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7436166/)
4. An improved version of the traditional Log-normal shadowing model (LNSM) propagation model [Distance measurement model based on RSSI in WSN](https://www.researchgate.net/publication/220279158_Distance_measurement_model_based_on_RSSI_in_WSN)

**Comment by AlbertHald** [comment]
### Literature for calibration of distance and trilateration using RSSI
https://www.researchgate.net/publication/356872554_Localisation_of_Inspection_Probes_in_A_Storage_Tank
